#ifndef _ROBOT_PARAMETER_H_
#define _ROBOT_PARAMETER_H_

#define CONFIG_FILE_NAME	"robot.conf"
#define VIDEO_DEVICE_NAME	"/dev/video3"
#define RS232_DEVICE_NAME	"/dev/ttySAC1"

#define MOTION_DEBUG_PORT 	50001
#define IMAGE_CAPTURE_PORT 	50002

#define BROADCAST_CONTROL_IP 	"255.255.255.255"
#define RECEIVE_CONTROL_PORT	3838

#define RECEIVE_MESSAGE_PORT	50004

/**/
#define PI			3.1415926

#define SHOW_PROCESS		FALSE
#define SHOW_PROCESS_IP		FALSE
#define SAVE_PROCESS_IP		FALSE	
#define SHOW_PROCESS_SL		FALSE	
#define SAVE_PROCESS_SL		FALSE
#define SHOW_PROCESS_BL		FALSE
#define SAVE_PROCESS_BL		FALSE
#define SAVE_JPG_FILE   	FALSE
#define SAVE_BMP_FILE		FALSE
#define SHOW_BALL			TRUE
#define SAVE_BEHAVIOR_FILE	FALSE

#endif /*_ROBOT_PARAMETER_*/


